//flutter pub add firebase_core// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgi8RM54NAHG9uBFJ0cYWAwyAR39sYdHo',
    appId: '1:709672656066:web:a808b06033bd44f69aaf5b',
    messagingSenderId: '709672656066',
    projectId: 'test-c15dd',
    authDomain: 'test-c15dd.firebaseapp.com',
    storageBucket: 'test-c15dd.appspot.com',
    measurementId: 'G-3MRNNJDQ4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNRF7X2eOtDC91HKhNocprgaqXWNMZVs8',
    appId: '1:709672656066:android:87aca846a5b7fda69aaf5b',
    messagingSenderId: '709672656066',
    projectId: 'test-c15dd',
    storageBucket: 'test-c15dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWIt50eFMyZePUZciK0EltxuLTSGSUhB8',
    appId: '1:709672656066:ios:95061f8d7fccc7859aaf5b',
    messagingSenderId: '709672656066',
    projectId: 'test-c15dd',
    storageBucket: 'test-c15dd.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWIt50eFMyZePUZciK0EltxuLTSGSUhB8',
    appId: '1:709672656066:ios:e143d260153250f49aaf5b',
    messagingSenderId: '709672656066',
    projectId: 'test-c15dd',
    storageBucket: 'test-c15dd.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
